
/**
* PeerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Peer.idl
* viernes 13 de mayo de 2022 06:43:28 PM CDT
*/

abstract public class PeerHelper
{
  private static String  _id = "IDL:Peer:1.0";

  public static void insert (org.omg.CORBA.Any a, Peer that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Peer extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (PeerHelper.id (), "Peer");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Peer read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PeerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Peer value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Peer narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Peer)
      return (Peer)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _PeerStub stub = new _PeerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Peer unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Peer)
      return (Peer)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _PeerStub stub = new _PeerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
