
/**
* PeerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Peer.idl
* viernes 13 de mayo de 2022 06:43:28 PM CDT
*/

public interface PeerOperations 
{
  void enviar_Mensaje (String mensaje);
  void recibir_Mensaje ();
} // interface PeerOperations
