
/**
* Peer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Peer.idl
* viernes 13 de mayo de 2022 06:43:28 PM CDT
*/

public interface Peer extends PeerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Peer
