
/**
* PeerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Peer.idl
* sábado 14 de mayo de 2022 02:09:04 AM CDT
*/

public final class PeerHolder implements org.omg.CORBA.portable.Streamable
{
  public Peer value = null;

  public PeerHolder ()
  {
  }

  public PeerHolder (Peer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PeerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PeerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PeerHelper.type ();
  }

}
