
/**
* Peer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Peer.idl
* sábado 14 de mayo de 2022 02:09:04 AM CDT
*/

public interface Peer extends PeerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Peer
