
/**
* PeerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Peer.idl
* domingo 15 de mayo de 2022 01:06:35 PM CDT
*/

public interface PeerOperations 
{
  void enviar_Mensaje (String mensaje);
  void recibir_Mensaje ();
  void actualizar_Lista_Peers (String peers);
} // interface PeerOperations
