
/**
* PeerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Peer.idl
* sábado 14 de mayo de 2022 02:09:04 AM CDT
*/

public interface PeerOperations 
{
  void enviar_Mensaje (String mensaje);
  void recibir_Mensaje ();
  void actualizar_Lista_Peers (String peers);
} // interface PeerOperations
